import json
import re

import pandas as pd
from json_repair import repair_json

from dataflow import get_logger
from dataflow.core import OperatorABC
from dataflow.utils.registry import OPERATOR_REGISTRY
from dataflow.utils.storage import DataFlowStorage


@OPERATOR_REGISTRY.register()
class JsonParseFilter(OperatorABC):
    # 支持的类型映射
    TYPE_MAP = {
        "str": str,
        "string": str,
        "int": int,
        "integer": int,
        "float": float,
        "bool": bool,
        "boolean": bool,
        "list": list,
        "array": list,
        "dict": dict,
        "object": dict,
        "none": type(None),
        "null": type(None),
    }

    def __init__(
        self,
        required_fields: list | None = None,
        field_types: dict[str, str] | None = None,
        field_values: dict | None = None,
        field_patterns: dict | None = None,
        field_ranges: dict | None = None,
    ):
        self.logger = get_logger()
        self.logger.info(f"Initializing {self.__class__.__name__}")

        # 验证配置参数
        self.required_fields = required_fields or []

        # 将字符串类型转换为实际类型
        self.field_types = {}
        if field_types:
            for field, type_str in field_types.items():
                type_str_lower = (
                    type_str.lower() if isinstance(type_str, str) else type_str
                )
                if type_str_lower in self.TYPE_MAP:
                    self.field_types[field] = self.TYPE_MAP[type_str_lower]
                else:
                    self.logger.warning(
                        f"Unknown type '{type_str}' for field '{field}', skipping"
                    )

        self.field_values = field_values or {}
        self.field_patterns = field_patterns or {}
        self.field_ranges = field_ranges or {}

    @staticmethod
    def get_desc(lang: str = "zh"):
        if lang == "zh":
            return (
                "尝试以 json 格式解析输入字段，将解析结果放入输出字段，并可选地检查 JSON 字段是否符合预期。\n"
                "如果解析失败或字段检查不通过，就丢弃条目。\n\n"
                "初始化参数：\n"
                "- required_fields：可选，需要检查的字段列表，例如 ['name', 'age']\n"
                "- field_types：可选，字段类型检查字典，类型用字符串表示，例如 {'name': 'str', 'age': 'int'}\n"
                "  支持的类型：str, int, float, bool, list, dict, none\n"
                "- field_values：可选，字段值检查字典，例如 {'status': 'ok', 'type': 'article'}\n"
                "- field_patterns：可选，字段正则匹配字典，例如 {'email': r'^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$'}\n"
                "- field_ranges：可选，数值范围检查字典，例如 {'age': (0, 150), 'score': (0, 100)}\n\n"
                "run 方法参数：\n"
                "- input_key：输入字段名\n"
                "- output_key：输出字段名\n\n"
                "使用场景：\n"
                "使用 LLM 生成 json 结果后，对结果进行解析和验证。"
            )
        elif lang == "en":
            return (
                "Parse input field as JSON, store result in output field, with optional field validation.\n"
                "Entries with invalid JSON or failed field checks are dropped.\n\n"
                "Init parameters:\n"
                "- required_fields: optional, list of required field names, e.g. ['name', 'age']\n"
                "- field_types: optional, dict of field type checks (as strings), e.g. {'name': 'str', 'age': 'int'}\n"
                "  Supported types: str, int, float, bool, list, dict, none\n"
                "- field_values: optional, dict of exact value checks, e.g. {'status': 'ok', 'type': 'article'}\n"
                "- field_patterns: optional, dict of regex patterns, e.g. {'email': r'^[\\w.-]+@[\\w.-]+\\.[a-z]{2,}$'}\n"
                "- field_ranges: optional, dict of numeric ranges, e.g. {'age': (0, 150), 'score': (0, 100)}\n\n"
                "run method parameters:\n"
                "- input_key: input column name\n"
                "- output_key: output column name\n\n"
                "Use case:\n"
                "Parse and validate JSON results generated by LLM."
            )
        else:
            return "JsonParseFilter"

    def _validate_json_fields(self, data: dict) -> tuple[bool, str]:
        """
        验证 JSON 字段是否符合预期。

        Args:
            data: 解析后的 JSON 数据

        Returns:
            (验证是否通过，失败原因)
        """
        # 检查必填字段
        if self.required_fields:
            for field in self.required_fields:
                if field not in data:
                    return False, f"Missing required field: {field}"

        # 检查字段类型
        if self.field_types:
            for field, expected_type in self.field_types.items():
                if field in data:
                    if not isinstance(data[field], expected_type):
                        return (
                            False,
                            f"Field '{field}' type mismatch: expected {expected_type.__name__}, got {type(data[field]).__name__}",
                        )

        # 检查字段值精确匹配
        if self.field_values:
            for field, expected_value in self.field_values.items():
                if field in data:
                    if data[field] != expected_value:
                        return (
                            False,
                            f"Field '{field}' value mismatch: expected {expected_value!r}, got {data[field]!r}",
                        )

        # 检查字段正则匹配
        if self.field_patterns:
            for field, pattern in self.field_patterns.items():
                if field in data:
                    value = data[field]
                    if not isinstance(value, str):
                        return (
                            False,
                            f"Field '{field}' pattern check requires string, got {type(value).__name__}",
                        )
                    if not re.match(pattern, value):
                        return (
                            False,
                            f"Field '{field}' pattern mismatch: '{value}' does not match '{pattern}'",
                        )

        # 检查数值范围
        if self.field_ranges:
            for field, (min_val, max_val) in self.field_ranges.items():
                if field in data:
                    value = data[field]
                    if not isinstance(value, (int, float)):
                        return (
                            False,
                            f"Field '{field}' range check requires number, got {type(value).__name__}",
                        )
                    if value < min_val or value > max_val:
                        return (
                            False,
                            f"Field '{field}' out of range: {value} not in [{min_val}, {max_val}]",
                        )

        return True, ""

    def run(
        self,
        storage: DataFlowStorage,
        input_key: str,
        output_key: str,
    ) -> str:
        self.input_key = input_key
        self.output_key = output_key

        df: pd.DataFrame = storage.read("dataframe")
        rtn: list[dict] = []
        total_count = len(df)
        invalid_json_count = 0
        validation_failures: dict[str, int] = {}

        for x in df.to_dict(orient="records"):
            # 检查输入字段是否存在且为字符串
            if (
                input_key not in x
                or x[input_key] is None
                or not isinstance(x[input_key], str)
            ):
                continue

            json_string: str = x[input_key]
            # 清理可能的 markdown 代码块标记
            json_string = (
                json_string.strip(" \n")
                .removeprefix("```json")
                .removesuffix("```")
                .removeprefix("```")
                .removesuffix("```")
            )

            # 尝试修复并解析 JSON
            try:
                d = repair_json(json_string, return_objects=True)
                # repair_json 几乎不抛异常，需要检查返回值有效性
                if not isinstance(d, dict):
                    self.logger.debug(
                        f"repair_json returned non-dict: {type(d).__name__}"
                    )
                    invalid_json_count += 1
                    continue
            except (TypeError, ValueError) as e:
                self.logger.debug(f"repair_json failed: {e}")
                invalid_json_count += 1
                continue

            # 确保解析结果是字典
            if not isinstance(d, dict):
                self.logger.debug(f"JSON is not an object: {type(d)}")
                invalid_json_count += 1
                continue

            # 检查字段是否符合预期
            valid, reason = self._validate_json_fields(d)
            if not valid:
                # 统计失败原因
                if "Missing required field" in reason:
                    validation_failures["missing_field"] = (
                        validation_failures.get("missing_field", 0) + 1
                    )
                elif "type mismatch" in reason:
                    validation_failures["type_mismatch"] = (
                        validation_failures.get("type_mismatch", 0) + 1
                    )
                elif "value mismatch" in reason:
                    validation_failures["value_mismatch"] = (
                        validation_failures.get("value_mismatch", 0) + 1
                    )
                elif "pattern mismatch" in reason:
                    validation_failures["pattern_mismatch"] = (
                        validation_failures.get("pattern_mismatch", 0) + 1
                    )
                elif "out of range" in reason:
                    validation_failures["range_mismatch"] = (
                        validation_failures.get("range_mismatch", 0) + 1
                    )
                else:
                    validation_failures["other"] = (
                        validation_failures.get("other", 0) + 1
                    )

                self.logger.debug(f"Validation failed: {reason}")
                continue

            # 解析和验证通过，添加到结果
            x[output_key] = d
            rtn.append(x)

        # 构建统计信息
        stats_parts = [
            f"Total: {total_count}",
            f"Passed: {len(rtn)}",
            f"Invalid JSON: {invalid_json_count}",
        ]
        for failure_type, count in validation_failures.items():
            stats_parts.append(f"{failure_type}: {count}")

        self.logger.info(f"Filtering complete. " + ", ".join(stats_parts))

        filtered_df = pd.DataFrame(rtn)
        storage.write(filtered_df)
        self.logger.info(
            f"Filtering completed. Total records passing filter: {len(filtered_df)}."
        )
        return output_key
